site_name: SpeechToolkit
copyright: '&copy; 2024 <a href="https://ml-for-speech.github.io/">ML for Speech</a>. All docs are on our <a href="https://github.com/ml-for-speech/speechtoolkit">GitHub Repository</a>.'
# repo_url: https://github.com/ml-for-speech/speechtoolkit

theme:
  name: mkdocs
  highlightjs: true
  hljs_languages:
    - python
    - yaml
    - json
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 191  # /
  custom_dir: docs_theme
markdown_extensions:
  - admonition
  - codehilite
extra_css:
  - css/custom.css